name: "Update database"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
    - uses: actions/cache@v3
      with:
        path: cache
        key: crawling-cache
    - uses: Project-Env/project-env-github-action@v1.4.0
    - run: mvn -B verify exec:exec -Dexec.executable="java" -Dexec.args="-classpath %classpath ch.projectplants.database.PlantsDatabaseCreator database.json cache"
    - uses: peter-evans/create-pull-request@v5
      with:
        title: 'update plants database'
        body: 'Updated plants database with latest info'
        commit-message: 'update plants database'
        branch: 'feature/update-plants-database'
